version: '3.7'

volumes:
  db-data: {}

services:
  db:
    build:
      context: ./backend
      dockerfile: ./compose/postgres/Dockerfile
    env_file:
      - .envs
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
      dockerfile: ./compose/django/Dockerfile
    env_file:
      - .envs
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ./compose/django/dev_entrypoint.sh

  telegram:
    build:
      context: ./telegram_bot
      dockerfile: ./compose/DockerFile
    env_file:
      - .envs
    volumes:
      - ./telegram_bot:/app
    depends_on:
      - app
    command: ./compose/dev_entrypoint.sh