# Generated by Django 3.1.2 on 2020-10-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('telegram_id', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('topic', models.TextField()),
                ('message', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('New', 'New'), ('InProgress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', related_query_name='tickets', to='customer.customer')),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
