# Generated by Django 3.1.2 on 2020-10-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
